### ISSUE TITLE
Region configuration option

### ISSUE THREAD

**Issue by ajagnanan** [k-kinzal/grunt-lambda-upload#2]
Hello, can we add an option to make the region configurable? I keep getting "ConfigError: Missing region in config" even though using the aws default region environment variable.

**Comment by k-kinzal** [comment]
Hi @ajagnanan 
Please specify the `AWS_REGION` or `AMAZON_REGION` in the environment variable.
https://github.com/aws/aws-sdk-js/blob/fb0f95f43ea958846d932bb4e79934a4a548155f/lib/aws.js#L47

Or please set the `region=[your region]` in `~/.aws/config`.
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

**Comment by ajagnanan** [comment]
Cool the env variable worked. Maybe its still best to add a region option though, in case functions need to be uploaded to different regions. Thanks!
